# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{indexotron}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["j05h"]
  s.date = %q{2010-07-29}
  s.default_executable = %q{ndxo}
  s.description = %q{A very personal search index for any site you like}
  s.email = %q{josh@kleinpeter.org}
  s.executables = ["ndxo"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/ndxo",
     "lib/indexotron.rb",
     "lib/indexotron/runner.rb",
     "test/helper.rb",
     "test/test_indexotron.rb",
     "test/test_runner.rb"
  ]
  s.homepage = %q{http://github.com/j05h/indexotron}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A personal search index for any site you like}
  s.test_files = [
    "test/helper.rb",
     "test/test_indexotron.rb",
     "test/test_runner.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<rubberband>, [">= 0.0.2"])
      s.add_runtime_dependency(%q<anemone>, ["= 0.4.0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<rubberband>, [">= 0.0.2"])
      s.add_dependency(%q<anemone>, ["= 0.4.0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<rubberband>, [">= 0.0.2"])
    s.add_dependency(%q<anemone>, ["= 0.4.0"])
  end
end

